services:
  redis:
    image: redis:8.2-alpine3.22
    container_name: redis-pipeline-demo
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
